apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
        - name: log-message-processor
          image: registry.digitalocean.com/kube-app-registry/log-message-processor
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: "log_channel"
            - name: ZIPKIN_URL
              value: "http://zipkin:9411/api/v1/spans"
